global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/metrics'

  - job_name: 'blockchain'
    static_configs:
      - targets: ['besu:8545']
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '(.*)'
        replacement: '${1}'

  - job_name: 'ai-agents'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/agent-metrics'

  - job_name: 'workflow-orchestrator'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/workflow-metrics'

  - job_name: 'workflow_metrics'
    static_configs:
      - targets: ['monitoring:3000']
    metrics_path: '/metrics'

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']